// <auto-generated />
using System;
using CustomerSupportBot.Adapters.Persistence.EfCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CustomerSupportBot.Adapters.Persistence.Migrations
{
    [DbContext(typeof(CustomerSupportDbContext))]
    partial class CustomerSupportDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CustomerSupportBot.Adapters.Persistence.EfCore.Entities.Analytics.RatingEntity", b =>
                {
                    b.Property<string>("SessionId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("session_id");

                    b.Property<string>("Feedback")
                        .HasColumnType("text")
                        .HasColumnName("feedback");

                    b.Property<string>("Id")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("id");

                    b.Property<DateTime>("RatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("rated_at");

                    b.Property<int>("Stars")
                        .HasColumnType("integer")
                        .HasColumnName("stars");

                    b.HasKey("SessionId");

                    b.HasIndex("RatedAt")
                        .IsDescending()
                        .HasDatabaseName("ix_ratings_rated_at");

                    b.ToTable("ratings", "analytics", t =>
                        {
                            t.HasCheckConstraint("ck_ratings_stars_range", "stars BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("CustomerSupportBot.Adapters.Persistence.EfCore.Entities.Analytics.SlaEventEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("action");

                    b.Property<int>("AgeSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("age_seconds");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kind");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("severity");

                    b.Property<string>("TargetId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("target_id");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamptz")
                        .HasColumnName("timestamp");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp")
                        .IsDescending()
                        .HasDatabaseName("ix_sla_events_timestamp");

                    b.HasIndex("Kind", "TargetId", "Severity")
                        .HasDatabaseName("ix_sla_events_kind_target_severity");

                    b.ToTable("sla_events", "analytics");
                });

            modelBuilder.Entity("CustomerSupportBot.Adapters.Persistence.EfCore.Entities.Auth.RefreshTokenEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("expires_at");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("replaced_by_token_hash");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token_hash");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ux_refresh_tokens_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_tokens_user");

                    b.ToTable("refresh_tokens", "auth");
                });

            modelBuilder.Entity("CustomerSupportBot.Adapters.Persistence.EfCore.Entities.Auth.UserEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_login_at");

                    b.Property<string>("LinkedAgentId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("linked_agent_id");

                    b.Property<string>("LinkedCustomerId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("linked_customer_id");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ux_users_username");

                    b.ToTable("users", "auth");
                });

            modelBuilder.Entity("CustomerSupportBot.Adapters.Persistence.EfCore.Entities.Catalog.CategoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name")
                        .UseCollation("und-u-ks-level1");

                    b.HasKey("Id");

                    b.ToTable("categories", "catalog");
                });

            modelBuilder.Entity("CustomerSupportBot.Adapters.Persistence.EfCore.Entities.Catalog.ComplaintEntity", b =>
                {
                    b.Property<long>("Code")
                        .HasColumnType("bigint")
                        .HasColumnName("code");

                    b.Property<string>("Complaint")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("complaint");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint")
                        .HasColumnName("customer_id");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("order_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("status");

                    b.HasKey("Code");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_complaints_customer_id");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_complaints_order_id");

                    b.ToTable("complaints", "catalog");
                });

            modelBuilder.Entity("CustomerSupportBot.Adapters.Persistence.EfCore.Entities.Catalog.CustomerEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("full_name");

                    b.Property<string>("Phone")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("phone");

                    b.HasKey("Id");

                    b.HasIndex("FullName")
                        .HasDatabaseName("ix_customers_full_name");

                    b.ToTable("customers", "catalog");
                });

            modelBuilder.Entity("CustomerSupportBot.Adapters.Persistence.EfCore.Entities.Catalog.OrderDetailEntity", b =>
                {
                    b.Property<long>("OrderCode")
                        .HasColumnType("bigint")
                        .HasColumnName("order_code");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.HasKey("OrderCode", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("order_details", "catalog");
                });

            modelBuilder.Entity("CustomerSupportBot.Adapters.Persistence.EfCore.Entities.Catalog.OrderEntity", b =>
                {
                    b.Property<long>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("code");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Code"));

                    b.Property<string>("CancelReason")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("cancel_reason");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("cancelled_at");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint")
                        .HasColumnName("customer_id");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("order_date");

                    b.Property<string>("ReturnReason")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("return_reason");

                    b.Property<DateTime?>("ReturnRequestedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("return_requested_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("status");

                    b.HasKey("Code");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_orders_customer_id");

                    b.ToTable("orders", "catalog");
                });

            modelBuilder.Entity("CustomerSupportBot.Adapters.Persistence.EfCore.Entities.Catalog.ProductEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name")
                        .UseCollation("und-u-ks-level1");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("price");

                    b.Property<int>("Stock")
                        .HasColumnType("integer")
                        .HasColumnName("stock");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_products_name");

                    b.ToTable("products", "catalog");
                });

            modelBuilder.Entity("CustomerSupportBot.Adapters.Persistence.EfCore.Entities.Chat.ChatBridgeMessageEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("HumanAgent")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("human_agent");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("message_id");

                    b.Property<string>("Sender")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("sender");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("session_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.HasKey("Id");

                    b.HasIndex("MessageId")
                        .HasDatabaseName("ix_bridge_messages_message_id");

                    b.HasIndex("SessionId", "Id")
                        .HasDatabaseName("ix_bridge_messages_session");

                    b.ToTable("bridge_messages", "chat");
                });

            modelBuilder.Entity("CustomerSupportBot.Adapters.Persistence.EfCore.Entities.Chat.ChatSessionModeEntity", b =>
                {
                    b.Property<string>("SessionId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("session_id");

                    b.Property<DateTime?>("EnteredAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("entered_at");

                    b.Property<string>("HumanAgent")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("human_agent");

                    b.Property<DateTime?>("LastActivityAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_activity_at");

                    b.Property<int>("MessageCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("message_count");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("mode");

                    b.HasKey("SessionId");

                    b.HasIndex("Mode")
                        .HasDatabaseName("ix_session_modes_active")
                        .HasFilter("mode = 'Human'");

                    b.ToTable("session_modes", "chat");
                });

            modelBuilder.Entity("CustomerSupportBot.Adapters.Persistence.EfCore.Entities.Chat.MessageEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("role");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("session_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "Id")
                        .HasDatabaseName("ix_messages_session");

                    b.ToTable("messages", "chat");
                });

            modelBuilder.Entity("CustomerSupportBot.Adapters.Persistence.EfCore.Entities.Chat.SessionEntity", b =>
                {
                    b.Property<string>("SessionId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("session_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("LastActivity")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_activity");

                    b.Property<string>("StateJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("state");

                    b.HasKey("SessionId");

                    b.HasIndex("LastActivity")
                        .IsDescending()
                        .HasDatabaseName("ix_sessions_last_activity");

                    b.ToTable("sessions", "chat");
                });

            modelBuilder.Entity("CustomerSupportBot.Adapters.Persistence.EfCore.Entities.Hitl.ApprovalRequestEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("id");

                    b.Property<string>("AgentName")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("agent_name");

                    b.Property<string>("CustomerId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("customer_id");

                    b.Property<DateTime?>("CustomerSeenAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("customer_seen_at");

                    b.Property<DateTime?>("DecidedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("decided_at");

                    b.Property<string>("DecidedBy")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("decided_by");

                    b.Property<string>("DecisionReason")
                        .HasColumnType("text")
                        .HasColumnName("decision_reason");

                    b.Property<DateTime?>("ExecutedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("executed_at");

                    b.Property<string>("ExecutionResult")
                        .HasColumnType("text")
                        .HasColumnName("execution_result");

                    b.Property<string>("Justification")
                        .HasColumnType("text")
                        .HasColumnName("justification");

                    b.Property<string>("ParametersJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("parameters");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("requested_at");

                    b.Property<string>("SessionId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("session_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<int>("TimeoutSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("timeout_seconds");

                    b.Property<string>("ToolName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("tool_name");

                    b.Property<string>("TraceId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("trace_id");

                    b.Property<string>("UserQuery")
                        .HasColumnType("text")
                        .HasColumnName("user_query");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_approvals_customer_id");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_approvals_session_id");

                    b.HasIndex("Status", "RequestedAt")
                        .HasDatabaseName("ix_approvals_status_requested_at");

                    b.ToTable("approval_requests", "hitl");
                });

            modelBuilder.Entity("CustomerSupportBot.Adapters.Persistence.EfCore.Entities.Hitl.EscalationEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AcknowledgedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("acknowledged_at");

                    b.Property<string>("AgentName")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("agent_name");

                    b.Property<string>("AssignedTo")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("assigned_to");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("MissingContextJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("missing_context");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<string>("Resolution")
                        .HasColumnType("text")
                        .HasColumnName("resolution");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("resolved_at");

                    b.Property<string>("ResponseSummary")
                        .HasColumnType("text")
                        .HasColumnName("response_summary");

                    b.Property<string>("SessionId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("session_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<string>("TraceId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("trace_id");

                    b.Property<string>("UserQuery")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_query");

                    b.HasKey("Id");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_escalations_session_open")
                        .HasFilter("status IN ('Open', 'Acknowledged')");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("ix_escalations_status_created_at");

                    b.ToTable("escalations", "hitl");
                });

            modelBuilder.Entity("CustomerSupportBot.Adapters.Persistence.EfCore.Entities.Hitl.HumanAgentEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<int>("CurrentLoad")
                        .HasColumnType("integer")
                        .HasColumnName("current_load");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("LanguagesJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("languages");

                    b.Property<DateTime?>("LastAssignedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_assigned_at");

                    b.Property<int>("MaxConcurrentLoad")
                        .HasColumnType("integer")
                        .HasColumnName("max_concurrent_load");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<string>("SkillsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("skills");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_human_agents_active")
                        .HasFilter("is_active = true");

                    b.ToTable("human_agents", "hitl");
                });

            modelBuilder.Entity("CustomerSupportBot.Adapters.Persistence.EfCore.Entities.Improvement.LessonEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DecidedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("decided_at");

                    b.Property<string>("DecidedBy")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("decided_by");

                    b.Property<string>("DecisionReason")
                        .HasColumnType("text")
                        .HasColumnName("decision_reason");

                    b.Property<string>("LessonText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lesson_text");

                    b.Property<string>("Observation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("observation");

                    b.Property<string>("SourceTraceIdsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("source_trace_ids");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("SuggestedAgent")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("suggested_agent");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("title");

                    b.Property<string>("VectorMemoryId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("vector_memory_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("ix_lessons_created_at");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_lessons_status");

                    b.ToTable("lessons", "improvement");
                });

            modelBuilder.Entity("CustomerSupportBot.Adapters.Persistence.EfCore.Entities.Knowledge.KnowledgeArticleEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("category");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<int>("IndexedChunkCount")
                        .HasColumnType("integer")
                        .HasColumnName("indexed_chunk_count");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean")
                        .HasColumnName("is_published");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("IsPublished")
                        .HasDatabaseName("ix_articles_is_published");

                    b.HasIndex("UpdatedAt")
                        .IsDescending()
                        .HasDatabaseName("ix_articles_updated_at");

                    b.ToTable("articles", "knowledge");
                });

            modelBuilder.Entity("CustomerSupportBot.Adapters.Persistence.EfCore.Entities.Observability.LlmCallUsageEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CalledAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("called_at");

                    b.Property<decimal>("CostUsd")
                        .HasColumnType("numeric(12,8)")
                        .HasColumnName("cost_usd");

                    b.Property<double>("DurationMs")
                        .HasColumnType("double precision")
                        .HasColumnName("duration_ms");

                    b.Property<long>("InputTokens")
                        .HasColumnType("bigint")
                        .HasColumnName("input_tokens");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("model");

                    b.Property<long>("OutputTokens")
                        .HasColumnType("bigint")
                        .HasColumnName("output_tokens");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("provider");

                    b.HasKey("Id");

                    b.HasIndex("CalledAt")
                        .IsDescending()
                        .HasDatabaseName("ix_llm_call_usage_called_at");

                    b.HasIndex("Model")
                        .HasDatabaseName("ix_llm_call_usage_model");

                    b.ToTable("llm_call_usage", "observability");
                });

            modelBuilder.Entity("CustomerSupportBot.Adapters.Persistence.EfCore.Entities.Observability.ReasoningTraceEntity", b =>
                {
                    b.Property<string>("TraceId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("trace_id");

                    b.Property<string>("AgentVisitsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("agent_visits");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("completed_at");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<long>("EstimatedTokens")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("estimated_tokens");

                    b.Property<string>("FinalCritiqueJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("final_critique");

                    b.Property<string>("FinalResponse")
                        .HasColumnType("text")
                        .HasColumnName("final_response");

                    b.Property<string>("FirstDraftResponse")
                        .HasColumnType("text")
                        .HasColumnName("first_draft_response");

                    b.Property<int>("IterationCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("iteration_count");

                    b.Property<string>("PlanningJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("planning");

                    b.Property<string>("ReasoningJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("reasoning");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("session_id");

                    b.Property<string>("SpecialistReasoningsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("specialist_reasonings");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("started_at");

                    b.Property<string>("TerminationReason")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("termination_reason");

                    b.Property<string>("ToolCallsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("tool_calls");

                    b.Property<string>("UserQuery")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_query");

                    b.Property<bool>("WasRevised")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("was_revised");

                    b.HasKey("TraceId");

                    b.HasIndex("StartedAt")
                        .IsDescending()
                        .HasDatabaseName("ix_traces_started");

                    b.HasIndex("SessionId", "StartedAt")
                        .HasDatabaseName("ix_traces_session_started");

                    b.ToTable("reasoning_traces", "observability");
                });

            modelBuilder.Entity("CustomerSupportBot.Adapters.Persistence.EfCore.Entities.Personalization.CustomerProfileEntity", b =>
                {
                    b.Property<string>("CustomerId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("customer_id");

                    b.Property<string>("AdminNote")
                        .HasColumnType("text")
                        .HasColumnName("admin_note");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("IntentFrequencyJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("intent_frequency");

                    b.Property<DateTime?>("LastConsolidatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_consolidated_at");

                    b.Property<DateTime>("LastInteractionAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_interaction_at");

                    b.Property<string>("PreferredLanguage")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("preferred_language");

                    b.Property<string>("PreferredTone")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("preferred_tone");

                    b.Property<string>("ProductInterestsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("product_interests");

                    b.Property<string>("RecentRatingsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("recent_ratings");

                    b.Property<string>("Summary")
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<int>("TotalSessions")
                        .HasColumnType("integer")
                        .HasColumnName("total_sessions");

                    b.Property<int>("TotalTurns")
                        .HasColumnType("integer")
                        .HasColumnName("total_turns");

                    b.HasKey("CustomerId");

                    b.HasIndex("LastInteractionAt")
                        .IsDescending()
                        .HasDatabaseName("ix_customer_profiles_last_interaction_at");

                    b.ToTable("customer_profiles", "personalization");
                });

            modelBuilder.Entity("CustomerSupportBot.Adapters.Persistence.EfCore.Entities.Auth.RefreshTokenEntity", b =>
                {
                    b.HasOne("CustomerSupportBot.Adapters.Persistence.EfCore.Entities.Auth.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_user");
                });

            modelBuilder.Entity("CustomerSupportBot.Adapters.Persistence.EfCore.Entities.Catalog.OrderDetailEntity", b =>
                {
                    b.HasOne("CustomerSupportBot.Adapters.Persistence.EfCore.Entities.Catalog.OrderEntity", "Order")
                        .WithMany("Details")
                        .HasForeignKey("OrderCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CustomerSupportBot.Adapters.Persistence.EfCore.Entities.Catalog.ProductEntity", "Product")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CustomerSupportBot.Adapters.Persistence.EfCore.Entities.Catalog.ProductEntity", b =>
                {
                    b.HasOne("CustomerSupportBot.Adapters.Persistence.EfCore.Entities.Catalog.CategoryEntity", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CustomerSupportBot.Adapters.Persistence.EfCore.Entities.Chat.MessageEntity", b =>
                {
                    b.HasOne("CustomerSupportBot.Adapters.Persistence.EfCore.Entities.Chat.SessionEntity", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_messages_session");
                });

            modelBuilder.Entity("CustomerSupportBot.Adapters.Persistence.EfCore.Entities.Catalog.CategoryEntity", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("CustomerSupportBot.Adapters.Persistence.EfCore.Entities.Catalog.OrderEntity", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("CustomerSupportBot.Adapters.Persistence.EfCore.Entities.Catalog.ProductEntity", b =>
                {
                    b.Navigation("OrderDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
