// <auto-generated />
using System;
using CustomerSupportBot.Api.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CustomerSupportBot.Api.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CustomerSupportDbContext))]
    [Migration("20260510152005_AddLinkedAgentIdToUsers")]
    partial class AddLinkedAgentIdToUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CustomerSupportBot.Api.Infrastructure.Persistence.Entities.Analytics.RatingEntity", b =>
                {
                    b.Property<string>("SessionId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("session_id");

                    b.Property<string>("Feedback")
                        .HasColumnType("text")
                        .HasColumnName("feedback");

                    b.Property<string>("Id")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("id");

                    b.Property<DateTime>("RatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("rated_at");

                    b.Property<int>("Stars")
                        .HasColumnType("integer")
                        .HasColumnName("stars");

                    b.HasKey("SessionId");

                    b.HasIndex("RatedAt")
                        .IsDescending()
                        .HasDatabaseName("ix_ratings_rated_at");

                    b.ToTable("ratings", "analytics", t =>
                        {
                            t.HasCheckConstraint("ck_ratings_stars_range", "stars BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("CustomerSupportBot.Api.Infrastructure.Persistence.Entities.Auth.RefreshTokenEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("expires_at");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("replaced_by_token_hash");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token_hash");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ux_refresh_tokens_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_tokens_user");

                    b.ToTable("refresh_tokens", "auth");
                });

            modelBuilder.Entity("CustomerSupportBot.Api.Infrastructure.Persistence.Entities.Auth.UserEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_login_at");

                    b.Property<string>("LinkedAgentId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("linked_agent_id");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ux_users_username");

                    b.ToTable("users", "auth");
                });

            modelBuilder.Entity("CustomerSupportBot.Api.Infrastructure.Persistence.Entities.Chat.ChatBridgeMessageEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("HumanAgent")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("human_agent");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("message_id");

                    b.Property<string>("Sender")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("sender");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("session_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.HasKey("Id");

                    b.HasIndex("MessageId")
                        .HasDatabaseName("ix_bridge_messages_message_id");

                    b.HasIndex("SessionId", "Id")
                        .HasDatabaseName("ix_bridge_messages_session");

                    b.ToTable("bridge_messages", "chat");
                });

            modelBuilder.Entity("CustomerSupportBot.Api.Infrastructure.Persistence.Entities.Chat.ChatSessionModeEntity", b =>
                {
                    b.Property<string>("SessionId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("session_id");

                    b.Property<DateTime?>("EnteredAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("entered_at");

                    b.Property<string>("HumanAgent")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("human_agent");

                    b.Property<DateTime?>("LastActivityAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_activity_at");

                    b.Property<int>("MessageCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("message_count");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("mode");

                    b.HasKey("SessionId");

                    b.HasIndex("Mode")
                        .HasDatabaseName("ix_session_modes_active")
                        .HasFilter("mode = 'Human'");

                    b.ToTable("session_modes", "chat");
                });

            modelBuilder.Entity("CustomerSupportBot.Api.Infrastructure.Persistence.Entities.Chat.MessageEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("role");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("session_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "Id")
                        .HasDatabaseName("ix_messages_session");

                    b.ToTable("messages", "chat");
                });

            modelBuilder.Entity("CustomerSupportBot.Api.Infrastructure.Persistence.Entities.Chat.SessionEntity", b =>
                {
                    b.Property<string>("SessionId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("session_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("LastActivity")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_activity");

                    b.Property<string>("StateJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("state");

                    b.HasKey("SessionId");

                    b.HasIndex("LastActivity")
                        .IsDescending()
                        .HasDatabaseName("ix_sessions_last_activity");

                    b.ToTable("sessions", "chat");
                });

            modelBuilder.Entity("CustomerSupportBot.Api.Infrastructure.Persistence.Entities.Hitl.ApprovalRequestEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("id");

                    b.Property<string>("AgentName")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("agent_name");

                    b.Property<DateTime?>("DecidedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("decided_at");

                    b.Property<string>("DecidedBy")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("decided_by");

                    b.Property<string>("DecisionReason")
                        .HasColumnType("text")
                        .HasColumnName("decision_reason");

                    b.Property<string>("Justification")
                        .HasColumnType("text")
                        .HasColumnName("justification");

                    b.Property<string>("ParametersJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("parameters");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("requested_at");

                    b.Property<string>("SessionId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("session_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<int>("TimeoutSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("timeout_seconds");

                    b.Property<string>("ToolName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("tool_name");

                    b.Property<string>("TraceId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("trace_id");

                    b.Property<string>("UserQuery")
                        .HasColumnType("text")
                        .HasColumnName("user_query");

                    b.HasKey("Id");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_approvals_session_id");

                    b.HasIndex("Status", "RequestedAt")
                        .HasDatabaseName("ix_approvals_status_requested_at");

                    b.ToTable("approval_requests", "hitl");
                });

            modelBuilder.Entity("CustomerSupportBot.Api.Infrastructure.Persistence.Entities.Hitl.EscalationEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AcknowledgedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("acknowledged_at");

                    b.Property<string>("AgentName")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("agent_name");

                    b.Property<string>("AssignedTo")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("assigned_to");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("MissingContextJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("missing_context");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<string>("Resolution")
                        .HasColumnType("text")
                        .HasColumnName("resolution");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("resolved_at");

                    b.Property<string>("ResponseSummary")
                        .HasColumnType("text")
                        .HasColumnName("response_summary");

                    b.Property<string>("SessionId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("session_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<string>("TraceId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("trace_id");

                    b.Property<string>("UserQuery")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_query");

                    b.HasKey("Id");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_escalations_session_open")
                        .HasFilter("status IN ('Open', 'Acknowledged')");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("ix_escalations_status_created_at");

                    b.ToTable("escalations", "hitl");
                });

            modelBuilder.Entity("CustomerSupportBot.Api.Infrastructure.Persistence.Entities.Hitl.HumanAgentEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<int>("CurrentLoad")
                        .HasColumnType("integer")
                        .HasColumnName("current_load");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("LanguagesJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("languages");

                    b.Property<DateTime?>("LastAssignedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_assigned_at");

                    b.Property<int>("MaxConcurrentLoad")
                        .HasColumnType("integer")
                        .HasColumnName("max_concurrent_load");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<string>("SkillsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("skills");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_human_agents_active")
                        .HasFilter("is_active = true");

                    b.ToTable("human_agents", "hitl");
                });

            modelBuilder.Entity("CustomerSupportBot.Api.Infrastructure.Persistence.Entities.Observability.ReasoningTraceEntity", b =>
                {
                    b.Property<string>("TraceId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("trace_id");

                    b.Property<string>("AgentVisitsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("agent_visits");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("completed_at");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<long>("EstimatedTokens")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("estimated_tokens");

                    b.Property<string>("FinalCritiqueJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("final_critique");

                    b.Property<string>("FinalResponse")
                        .HasColumnType("text")
                        .HasColumnName("final_response");

                    b.Property<string>("FirstDraftResponse")
                        .HasColumnType("text")
                        .HasColumnName("first_draft_response");

                    b.Property<int>("IterationCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("iteration_count");

                    b.Property<string>("PlanningJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("planning");

                    b.Property<string>("ReasoningJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("reasoning");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("session_id");

                    b.Property<string>("SpecialistReasoningsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("specialist_reasonings");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("started_at");

                    b.Property<string>("TerminationReason")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("termination_reason");

                    b.Property<string>("ToolCallsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("tool_calls");

                    b.Property<string>("UserQuery")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_query");

                    b.Property<bool>("WasRevised")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("was_revised");

                    b.HasKey("TraceId");

                    b.HasIndex("StartedAt")
                        .IsDescending()
                        .HasDatabaseName("ix_traces_started");

                    b.HasIndex("SessionId", "StartedAt")
                        .HasDatabaseName("ix_traces_session_started");

                    b.ToTable("reasoning_traces", "observability");
                });

            modelBuilder.Entity("CustomerSupportBot.Api.Infrastructure.Persistence.Entities.Auth.RefreshTokenEntity", b =>
                {
                    b.HasOne("CustomerSupportBot.Api.Infrastructure.Persistence.Entities.Auth.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_user");
                });

            modelBuilder.Entity("CustomerSupportBot.Api.Infrastructure.Persistence.Entities.Chat.MessageEntity", b =>
                {
                    b.HasOne("CustomerSupportBot.Api.Infrastructure.Persistence.Entities.Chat.SessionEntity", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_messages_session");
                });
#pragma warning restore 612, 618
        }
    }
}
